### ISSUE TITLE
找不到bitsandbytes包

### ISSUE THREAD

**Issue by googlebox007** [baichuan-inc/Baichuan2#126]
按照readme提供的安装步骤
pip install -r requeirest.txt
运行 streamlit run web_demo.py，webui无法正常打开，出现异常：
 streamlit run web_demo.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.107:8501

False
C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\bitsandbytes-0.40.2-py3.11.egg\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
2023-09-17 16:51:15.005 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 263, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\streamlit\runtime\caching\cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 311, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\streamlit\runtime\caching\cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "I:\Baichuan2\web_demo.py", line 72, in <module>
    main()
  File "I:\Baichuan2\web_demo.py", line 51, in main
    model, tokenizer = init_model()
                       ^^^^^^^^^^^^
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 211, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 240, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 266, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\Baichuan2\web_demo.py", line 14, in init_model
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\transformers\models\auto\auto_factory.py", line 550, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\transformers\dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\transformers\dynamic_module_utils.py", line 351, in get_cached_module_file
    get_cached_module_file(
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\transformers\dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\transformers\dynamic_module_utils.py", line 179, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: bitsandbytes. Run `pip install bitsandbytes`

反复重装bitsandbytes也没有用。
借鉴open-interpreter安装经验，到https://github.com/jllllll当中找到(https://github.com/jllllll/bitsandbytes-windows-webui)，在[Releases]当中通过适合的whell安装，我的电脑要安装https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
执行安装命令：python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

运行结果如下：
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting bitsandbytes==0.41.1
  Downloading https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl (152.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.7/152.7 MB 2.1 MB/s eta 0:00:00
Collecting scipy (from bitsandbytes==0.41.1)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/06/15/e73734f9170b66c6a84a0bd7e03586e87e77404e2eb8e34749fc49fa43f7/scipy-1.11.2-cp311-cp311-win_amd64.whl (44.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 MB 36.4 MB/s eta 0:00:00
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in c:\users\tuzhiyong\.conda\envs\baichuan1\lib\site-packages (from scipy->bitsandbytes==0.41.1) (1.26.0)
Installing collected packages: scipy, bitsandbytes
Successfully installed bitsandbytes-0.41.1 scipy-1.11.2

再次运行 streamlit run web_demo.py
正常：
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.107:8501

bin C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
A new version of the following files was downloaded from https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat:
- quantizer.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
Downloading (…)model.bin.index.json: 100%|█████████████████████████████████████████| 23.3k/23.3k [00:00<00:00, 170kB/s]
C:\Users\tuzhiyong\.conda\envs\baichuan1\Lib\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\tuzhiyong\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Downloading shards:   0%|                                                                        | 0/3 [00:00<?, ?it/s]
Downloading (…)l-00001-of-00003.bin:  53%|█████████████████████                   | 5.24G/9.97G [22:13<58:33, 1.35MB/s]

**Comment by jameswu2014** [comment]
如果bitsandbytes安装后还会有错，可以尝试源码编译安装。

**Comment by hmfjx123** [comment]
I have met a similar problem about bitsandbytes while Im using a win11 system. Try `pip install bitsandbytes-windows`. This helps in my environment.

**Comment by NorthWard** [comment]
遇到类似的问题, 重装了几次bitsandbytes没有效果.
运行了一下: `python -m bitsandbytes` 发现报错 `No module named 'scipy'`
再pip install scipy 问题就解决了
