### ISSUE TITLE
13B-fine-tune

### ISSUE THREAD

**Issue by liushifu12138** [baichuan-inc/Baichuan2#131]
0%|                                                                                                                                                                              | 0/6896 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/featurize/work/Baichuan2-main/fine-tune/fine-tune.py", line 153, in <module>
    train()
  File "/home/featurize/work/Baichuan2-main/fine-tune/fine-tune.py", line 147, in train
    trainer.train()
  File "/environment/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/environment/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/environment/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in training_step
    loss = self.compute_loss(model, inputs)
  File "/environment/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2704, in compute_loss
    outputs = model(**inputs)
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/featurize/.cache/huggingface/modules/transformers_modules/modeling_baichuan.py", line 693, in forward
    outputs = self.model(
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/featurize/.cache/huggingface/modules/transformers_modules/modeling_baichuan.py", line 392, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: 'weight' must be 2-D

**Comment by MrRace** [comment]
> 谢谢，是的，已经解决了

请问怎么解决的？
