### ISSUE TITLE
单机多卡微调报错，是命令哪个参数错了吗

### ISSUE THREAD

**Issue by dAItime001** [baichuan-inc/Baichuan2#143]
命令：
CUDA_VISIBLE_DEVICES=0,1,2 deepspeed --hostfile="" fine-tune.py      --report_to "none"     --data_path "multiturn_chat_0.8M.json" --model_name_or_path "../baichuan-inc/Baichuan2-13B-Chat"     --output_dir "output"     --model_max_length 512     --num_train_epochs 4     --per_device_train_batch_size 16     --gradient_accumulation_steps 1     --save_strategy epoch --learning_rate 2e-5     --lr_scheduler_type constant     --adam_beta1 0.9     --adam_beta2 0.98     --adam_epsilon 1e-8     --max_grad_norm 1.0     --weight_decay 1e-4     --warmup_ratio 0.0     --logging_steps 1     --gradient_checkpointing True     --deepspeed ds_config.json     --bf16 True     --tf32 True
报错日志：
[2023-09-19 15:16:44,393] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-19 15:16:45,978] [WARNING] [runner.py:203:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0,1,2: setting --include=localhost:0,1,2
[2023-09-19 15:16:45,979] [INFO] [runner.py:570:main] cmd = /root/anaconda3/envs/Baichuan2/bin/python3.10 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMl19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None fine-tune.py --report_to none --data_path multiturn_chat_0.8M.json --model_name_or_path ../baichuan-inc/Baichuan2-13B-Chat --output_dir output --model_max_length 512 --num_train_epochs 4 --per_device_train_batch_size 16 --gradient_accumulation_steps 1 --save_strategy epoch --learning_rate 2e-5 --lr_scheduler_type constant --adam_beta1 0.9 --adam_beta2 0.98 --adam_epsilon 1e-8 --max_grad_norm 1.0 --weight_decay 1e-4 --warmup_ratio 0.0 --logging_steps 1 --gradient_checkpointing True --deepspeed ds_config.json --bf16 True --tf32 True
[2023-09-19 15:16:47,538] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-19 15:16:49,006] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1, 2]}
[2023-09-19 15:16:49,006] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=3, node_rank=0
[2023-09-19 15:16:49,006] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2]})
[2023-09-19 15:16:49,006] [INFO] [launch.py:163:main] dist_world_size=3
[2023-09-19 15:16:49,006] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2
[2023-09-19 15:16:51,070] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-19 15:16:51,086] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-19 15:16:51,369] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-19 15:16:52,126] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-09-19 15:16:52,176] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-09-19 15:16:52,176] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2023-09-19 15:16:52,666] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-09-19 15:16:58,140] [INFO] [partition_parameters.py:347:__exit__] finished initializing model - num_params = 283, num_elems = 13.90B
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:08<00:00,  2.92s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:08<00:00,  2.92s/it]
Loading checkpoint shards:  67%|████████████████████████████████████████████████████████████████████████████████████████████                                              | 2/3 [00:09<00:04,  4.90s/it]Traceback (most recent call last):
  File "/root/GLM/Baichuan2/fine-tune/fine-tune.py", line 153, in <module>
    train()
  File "/root/GLM/Baichuan2/fine-tune/fine-tune.py", line 141, in train
    dataset = SupervisedDataset(
  File "/root/GLM/Baichuan2/fine-tune/fine-tune.py", line 51, in __init__
    self.data = json.load(open(data_path, encoding = 'utf-8'))
  File "/root/anaconda3/envs/Baichuan2/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/root/anaconda3/envs/Baichuan2/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/Baichuan2/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 348)
Traceback (most recent call last):
  File "/root/GLM/Baichuan2/fine-tune/fine-tune.py", line 153, in <module>
    train()
  File "/root/GLM/Baichuan2/fine-tune/fine-tune.py", line 141, in train
    dataset = SupervisedDataset(
  File "/root/GLM/Baichuan2/fine-tune/fine-tune.py", line 51, in __init__
    self.data = json.load(open(data_path, encoding = 'utf-8'))
  File "/root/anaconda3/envs/Baichuan2/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/root/anaconda3/envs/Baichuan2/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/Baichuan2/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 348)
[2023-09-19 15:17:10,050] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 14394
[2023-09-19 15:17:10,373] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 14395
[2023-09-19 15:17:10,374] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 14396
[2023-09-19 15:17:10,402] [ERROR] [launch.py:321:sigkill_handler] ['/root/anaconda3/envs/Baichuan2/bin/python3.10', '-u', 'fine-tune.py', '--local_rank=2', '--report_to', 'none', '--data_path', 'multiturn_chat_0.8M.json', '--model_name_or_path', '../baichuan-inc/Baichuan2-13B-Chat', '--output_dir', 'output', '--model_max_length', '512', '--num_train_epochs', '4', '--per_device_train_batch_size', '16', '--gradient_accumulation_steps', '1', '--save_strategy', 'epoch', '--learning_rate', '2e-5', '--lr_scheduler_type', 'constant', '--adam_beta1', '0.9', '--adam_beta2', '0.98', '--adam_epsilon', '1e-8', '--max_grad_norm', '1.0', '--weight_decay', '1e-4', '--warmup_ratio', '0.0', '--logging_steps', '1', '--gradient_checkpointing', 'True', '--deepspeed', 'ds_config.json', '--bf16', 'True', '--tf32', 'True'] exits with return code = 1

**Comment by jinqiupeter** [comment]
你的数据的格式有问题，第二行第一个字符那里有多余的字符：
raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: **line 2 column 1 (char 348)**

**Comment by dAItime001** [comment]
> 你的数据的格式有问题，第二行第一个字符那里有多余的字符： raise JSONDecodeError("Extra data", s, end) json.decoder.JSONDecodeError: Extra data: **line 2 column 1 (char 348)**

用的是官方示例数据啊：“multiturn_chat_0.8M.json”
{"instruction": "Human:你好，你能帮我解答一个问题吗？\nAssistant: 当然，请问有什么问题？\nHuman:我想了解人工智能的未来发展方向，你有什么想法吗？\nAssistant: 人工智能在未来的发展方向可能包括更强大的机器学
习算法，更先进的自然语言处理技术，以及更加智能的机器人。此外，人工智能还可以帮助解决许多现实世界的问题，例如自动化和改善医疗保健等领域。\nHuman:听起来很不错。人工智能可能在哪些方面面临挑战呢？\nAssistant:", "input": "", "output": " 人工智能面临的挑战包括数据隐私、安全和道德方面的问题，以及影响就业机会的自动化等问题。此外，人工智能可能会带来不平等和歧视风险，这也是需要关注的问题。"}
{"instruction": "Human:帮我生成一句有关夏天的英文名言。\nAssistant: \"Summertime is always the best of what might be.\" by Charles Bowden is a great summer quote. Would you like me to generate another one?\nHuman:再来一句关于阳光的英文名言。\nAssistant: \"Keep your face always toward the sunshine - and shadows will fall behind you.\" by Walt Whitman is a inspirational quote about sunshine. Do you need me to generate more quotes on this topic?\nHuman:不用了。现在请帮我解答一个问题，麻烦你解释一下人工智能机器学习的概念。\nAssistant: 当我们谈到人工智能时，常常会听到关于机器学习的概念。机器学习是人工智能研
究领域的一个子领域，它涵盖了许多不同的技术和算法。 简而言之，机器学习是一个让计算机自动从数据中学习的过程。它允许计算机通过观察特定数据集来自动推断有关该数据的模式和关系，从而“学习”如何更好地处理类似数据
。 是否需要更详细的解释或例子？\nHuman:不用了，谢谢你。那么你可以给我推荐一些好看的电影吗？\nAssistant:", "input": "", "output": " 当然可以。你对哪种类型的电影感兴趣？恐怖、浪漫、喜剧、动作或其他类型？"}
{"instruction": "Human: 你好，能告诉我今天天气怎么样吗？ \nAssistant: 当然可以，请问您所在的城市是哪里？ \nHuman: 我在纽约。 \nAssistant: 纽约今天晴间多云，气温最高约26摄氏度，最低约18摄氏度，记得注意保>暖喔。 \nHuman: 好的，谢谢你！ \nAssistant:", "input": "", "output": " 不客气，有其他需要帮忙的地方可以继续问我。"}

**Comment by zhaoedf** [comment]
> multiturn_chat_0.8M.json

你看文件里面的内容会发现，multiturn_chat_0.8M.json和repo里面的示例数据belle_chat_ramdon_10k.json的格式是不一样的。

**Comment by 1253113229** [comment]
我也遇到了同样的问题，我用的是自带的数据：belle_chat_ramdon_10k.json，然而还是报错：json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 22 column 1 (char 522)

**Comment by jinqiupeter** [comment]
> 我也遇到了同样的问题，我用的是自带的数据：belle_chat_ramdon_10k.json，然而还是报错：json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 22 column 1 (char 522)

错误说你的22行应该用双引号
