### ISSUE TITLE
 web demo正常启动之后测试对话就报错 The following `model_kwargs` are not used by the model: ['streamer'] 

### ISSUE THREAD

**Issue by Daxing** [baichuan-inc/Baichuan2#163]
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xchl/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xchl/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1213, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/home/xchl/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1105, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['streamer'] (note: typos in the generate arguments will also show up in this list)

**Comment by Daxing** [comment]
我用的模型是baichuan2-7B-chat的

**Comment by gulige** [comment]
cli_demo同样的错误，我用的模型是baichuan2-13B-chat

**Comment by gulige** [comment]
> cli_demo同样的错误，我用的模型是baichuan2-13B-chat

To upgrade transformers can solve this issue for me.
