### ISSUE TITLE
使用 transformers  8bit 在线量化的时候会报 `'BitsAndBytesConfig' object is not subscriptable` 错误

### ISSUE THREAD

**Issue by tianweidut** [baichuan-inc/Baichuan2#17]
# 错误复现
```python
>>> from transformers import AutoModelForCausalLM
>>> model = AutoModelForCausalLM.from_pretrained("pretrained/baichuan2-7b/base,, load_in_8bit=True, device_map="auto", trust_remote_code=True)
[2023-09-06 16:03:27,691] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-09-06 16:03:28.999241: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-06 16:03:30.314803: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liutianwei/.conda/envs/starwhale/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 488, in from_pretrained
    return model_class.from_pretrained(
  File "/home/liutianwei/.cache/huggingface/modules/transformers_modules/base/modeling_baichuan.py", line 779, in from_pretrained
    return super(BaichuanForCausalLM, cls).from_pretrained(
  File "/home/liutianwei/.conda/envs/starwhale/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/liutianwei/.cache/huggingface/modules/transformers_modules/base/modeling_baichuan.py", line 638, in __init__
    and config.quantization_config["load_in_4bit"]
TypeError: 'BitsAndBytesConfig' object is not subscriptable
>>> 
```
Baichuan2 7b-base, 7b-chat, 13b-base 和 13b-chat 都会报这个错误

# 解决方法
https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/blob/main/modeling_baichuan.py#L537 中需要判断 config.quantization_config 的类型

**Comment by daxia-daxia** [comment]
you can submit a PR to fix this. bro! or we will fix this later.

**Comment by jameswu2014** [comment]
This bug have beed fixed,you need pull the latest.

**Comment by zhl98** [comment]
您好，我还是遇到了这个问题。我看回复是已经修改了，是需要安装新版的transformer吗？我的transformers  是4.34.1。
问题是需要判断 config.quantization_config 的类型，加上isinstance(config.quantization_config, dict)，可是由于文件位于.cash中，每次运行都会变成原来的样子，因此直接修改没有作用。
