### ISSUE TITLE
V100（32G）加载百川2的13B的int8量化有问题？

### ISSUE THREAD

**Issue by cristianohello** [baichuan-inc/Baichuan2#170]
V100（32G）加载百川2的13B的int8量化有问题？而A6000没有问题。

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/__main__.py", line 96, in <module>
    generate_bug_report_information()
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/__main__.py", line 60, in generate_bug_report_information
    paths = find_file_recursive(os.getcwd(), '*cuda*so')
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

**Comment by lenmao** [comment]
您的错误信息表明在尝试加载百川2的13B模型时遇到了问题，特别是在使用 bitsandbytes 库时。错误 "RuntimeError: Something went wrong when trying to find file. Maybe you do not have a linux system?" 指出了在查找文件的过程中出现了问题。这个问题可能与您的系统环境、CUDA 配置或者 bitsandbytes 库的安装有关。

解决这个问题可能需要以下几个步骤：

确认操作系统：
确保您的操作系统是 Linux，因为 bitsandbytes 库可能专门为 Linux 系统设计。您可以在终端运行 uname -a 来检查操作系统信息。

检查 CUDA 和 GPU 驱动：
确保您的系统具有正确安装的 CUDA Toolkit 和 NVIDIA 驱动。可以使用 nvidia-smi 和 nvcc --version 来检查这些组件。

检查 Python 环境：
确保您使用的 Python 环境中正确安装了 bitsandbytes 库。您可以尝试重新安装或更新这个库。

确认硬件兼容性：
NVIDIA V100 和 A6000 可能对某些操作的支持不同，尤其是在进行量化时。请检查您的模型和代码是否与 V100 GPU 完全兼容。

检查 bitsandbytes 的使用：
确保您的代码中使用 bitsandbytes 的方式是正确的。您可能需要查阅 bitsandbytes 库的文档，确保您遵循了正确的使用方法。

搜索相关错误信息：
在网上搜索这个特定的错误信息，看看是否有其他用户遇到并解决了类似的问题。

请求技术支持：
如果以上步骤都无法解决问题，您可能需要联系 bitsandbytes 的开发者或者社区寻求帮助，或者在相关的技术论坛上寻求支持。

在处理这类问题时，请确保您对系统和环境的更改是谨慎的，以免造成更多的配置问题。
