### ISSUE TITLE
cuda老是报错，明明装好的CU118，同一台机器能跑chatGLM,就是跑不了百川？

### ISSUE THREAD

**Issue by kakabai** [baichuan-inc/Baichuan2#201]
(baichuan) D:\>python testpy.py
2.0.1+cu118
True
这里显示装好了。
(baichuan) D:\projact\Baichuan2-main>python cli_demo.py
False

===================================BUG REPORT===================================
D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('D')}
D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: D:\anaconda3\envs\baichuan did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "D:\projact\Baichuan2-main\cli_demo.py", line 8, in <module>
    from transformers.generation.utils import GenerationConfig
  File "D:\anaconda3\envs\baichuan\lib\site-packages\transformers\generation\utils.py", line 27, in <module>
    from ..integrations.deepspeed import is_deepspeed_zero3_enabled
  File "D:\anaconda3\envs\baichuan\lib\site-packages\transformers\integrations\__init__.py", line 14, in <module>
    from .bitsandbytes import (
  File "D:\anaconda3\envs\baichuan\lib\site-packages\transformers\integrations\bitsandbytes.py", line 11, in <module>
    import bitsandbytes as bnb
  File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
但是这里就是报错，怎么办？头疼。

**Comment by Jzhnakui** [comment]
> (baichuan) D:>python testpy.py 2.0.1+cu118 True 这里显示装好了。 (baichuan) D:\projact\Baichuan2-main>python cli_demo.py False
> 
> ===================================BUG REPORT=================================== D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
> # warn(msg)
> The following directories listed in your path were found to be non-existent: {WindowsPath('D')} D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: D:\anaconda3\envs\baichuan did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths... warn(msg) CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths... The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')} DEBUG: Possible options found for libcudart.so: set() CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.5. CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md CUDA SETUP: Loading binary D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so... argument of type 'WindowsPath' is not iterable CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected. CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA. CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO. CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local Traceback (most recent call last): File "D:\projact\Baichuan2-main\cli_demo.py", line 8, in from transformers.generation.utils import GenerationConfig File "D:\anaconda3\envs\baichuan\lib\site-packages\transformers\generation\utils.py", line 27, in from ..integrations.deepspeed import is_deepspeed_zero3_enabled File "D:\anaconda3\envs\baichuan\lib\site-packages\transformers\integrations__init__.py", line 14, in from .bitsandbytes import ( File "D:\anaconda3\envs\baichuan\lib\site-packages\transformers\integrations\bitsandbytes.py", line 11, in import bitsandbytes as bnb File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes__init__.py", line 6, in from . import cuda_setup, utils, research File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\research__init__.py", line 1, in from . import nn File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\research\nn__init__.py", line 1, in from .modules import LinearFP8Mixed, LinearFP8Global File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in from bitsandbytes.optim import GlobalOptimManager File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\optim__init__.py", line 6, in from bitsandbytes.cextension import COMPILED_WITH_CUDA File "D:\anaconda3\envs\baichuan\lib\site-packages\bitsandbytes\cextension.py", line 20, in raise RuntimeError(''' RuntimeError: CUDA Setup failed despite GPU being available. Please run the following command to get more information:
> 
> ```
>     python -m bitsandbytes
> 
>     Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
>     to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
>     and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
> ```
> 
> 但是这里就是报错，怎么办？头疼。
同样的问题，拟解决了吗

**Comment by Louis24** [comment]
我也是哦

**Comment by lvbinandylau** [comment]
只能用linux测试吗
