### ISSUE TITLE
Cannot quantize online.

### ISSUE THREAD

**Issue by RZ-Q** [baichuan-inc/Baichuan2#207]
When I call 
tokenizer = AutoTokenizer.from_pretrained(model_dir, use_fast=False, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_dir, device_map="auto", torch_dtype=torch.float16, trust_remote_code=True)
model = model.quantize(8).cuda() 
Comes a error:
Traceback (most recent call last):
  File "test_env.py", line 86, in <module>
    model = model.quantize(8).cuda() 
  File "/home/kouqian/.cache/huggingface/modules/transformers_modules/modeling_baichuan.py", line 737, in quantize
    raise ImportError(f"Needs QLinear to run quantize.")
ImportError: Needs QLinear to run quantize.

What's the problem? It can normally work without online quantize.

**Comment by kk19990709** [comment]
pip install bitsandbytes

**Comment by RZ-Q** [comment]
thanks, I'll try it
