### ISSUE TITLE
Tokennizer 初始化报错（add_token issues）

### ISSUE THREAD

**Issue by mokeyish** [baichuan-inc/Baichuan2#214]
这里 https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat/blob/main/tokenization_baichuan.py#L75
会提前调用 sp_model 导致报错。

请参考这个修复，https://github.com/huggingface/transformers/commit/2da8853775b61cde0894dee17c6c713aba711688

**Comment by DreamTeamWangbowen** [comment]
(default_env) root@5369cca9aa09:/data/wbw/codes/AIGC_inference/inference# python test_inference.py                                            2023-10-17 14:55:43,827 INFO [instantiator.py:21] Created a temporary directory at /tmp/tmp4orhcsi0
2023-10-17 14:55:43,827 INFO [instantiator.py:76] Writing /tmp/tmp4orhcsi0/_remote_module_non_scriptable.py
2023-10-17 14:55:44,049 INFO [baichuan2_inference.py:29] 量化加载模型...
Traceback (most recent call last):
  File "/data/wbw/codes/AIGC_inference/inference/test_inference.py", line 96, in <module>
    test_baichuan2_instance_quantized = test_inference.create_baichuan2_instance(
  File "/data/wbw/codes/AIGC_inference/inference/inference.py", line 40, in create_baichuan2_instance
    return BaiChuan2Instance(model_path, GPUS, quantized)
  File "/data/wbw/codes/AIGC_inference/inference/baichuan_inference/baichuan2/baichuan2_inference.py", line 24, in __init__
    self.init_model()
  File "/data/wbw/codes/AIGC_inference/inference/baichuan_inference/baichuan2/baichuan2_inference.py", line 48, in init_model
    self.tokenizer = AutoTokenizer.from_pretrained(
  File "/miniconda/envs/default_env/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 688, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class BaichuanTokenizer does not exist or is not currently imported.

I meet it too.
