### ISSUE TITLE
AttributeError: module 'torch.backends.cuda' has no attribute 'sdp_kernel'

### ISSUE THREAD

**Issue by huangdang111** [baichuan-inc/Baichuan2#229]
执行python cli_demo.py， 会弹出对话框，但是输入首个问题，就会报错，提示如下：
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/baichuan2/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/baichuan2/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/baichuan2/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/baichuan2/lib/python3.10/site-packages/transformers/generation/utils.py", line 1648, in generate
    return self.sample(
  File "/home/ubuntu/anaconda3/envs/baichuan2/lib/python3.10/site-packages/transformers/generation/utils.py", line 2730, in sample
    outputs = self(
  File "/home/ubuntu/anaconda3/envs/baichuan2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat-4bits/modeling_baichuan.py", line 684, in forward
    outputs = self.model(
  File "/home/ubuntu/anaconda3/envs/baichuan2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat-4bits/modeling_baichuan.py", line 461, in forward
    layer_outputs = decoder_layer(
  File "/home/ubuntu/anaconda3/envs/baichuan2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat-4bits/modeling_baichuan.py", line 273, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/ubuntu/anaconda3/envs/baichuan2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/ubuntu/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat-4bits/modeling_baichuan.py", line 233, in forward
    with torch.backends.cuda.sdp_kernel(enable_flash=True, enable_math=True, enable_mem_efficient=True):
AttributeError: module 'torch.backends.cuda' has no attribute 'sdp_kernel'

本地环境：
python3.10， CUDA 11.3， torch-1.12.1+cu113-cp310-cp310-linux_x86_64.whl  xformers-0.0.16-py310_cu11.3_pyt1.12.1.tar.bz2，
bitsandbytes  0.41.1（git下载本地，根据CUDA11.3 编译后安装的）

请问改如何解决？？

**Comment by tauriel07** [comment]
同问

**Comment by tauriel07** [comment]
> 好像是用到torch新版本里的功能。需要升级到 torch-2.0.1以上，为了升级这个，依次升级了显卡驱动、cuda、配套的torch、xformers、bitsandbytes 。 最后成功解决。 现在服务器基础软件的版本：CUDA11.8 及配套驱动、torch-2.0.1+cu118-cp310-cp310-linux_x86_64.whl、xformers-0.0.22.post3-py310_cu11.8.0_pyt2.0.1.tar.bz2、bitsandbytes 0.41.1（git下载本地，根据CUDA11.8编译后安装的）

感谢答复 我也是升级到2.0.0就解决了

**Comment by zzy347964399** [comment]
pip install transformers==4.33.1 tokenizers==0.13.3
