### ISSUE TITLE
streamlit运行cli_demo 遇到TypeError: _set_gradient_checkpointing() got an unexpected keyword argument 'enable'

### ISSUE THREAD

**Issue by wrl1224** [baichuan-inc/Baichuan2#251]
Traceback (most recent call last):
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "E:\wrl\PythonCode\Baichuan2\cli_demo.py", line 7, in <module>
    from transformers import AutoModelForCausalLM, AutoTokenizer
ImportError: cannot import name 'AutoModelForCausalLM' from 'transformers' (E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\__init__.py)
init model ...
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
2023-11-03 18:34:41.839 Uncaught app exception
Traceback (most recent call last):
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "E:\wrl\PythonCode\Baichuan2\cli_demo.py", line 91, in <module>
    main()
  File "E:\wrl\PythonCode\Baichuan2\cli_demo.py", line 52, in main
    model, tokenizer = init_model()
  File "E:\wrl\PythonCode\Baichuan2\cli_demo.py", line 13, in init_model
    model = AutoModelForCausalLM.from_pretrained(
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 670, in from_pretrained
    return super(BaichuanForCausalLM, cls).from_pretrained(pretrained_model_name_or_path, *model_args,
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\modeling_utils.py", line 3236, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 539, in __init__
    self.model = BaichuanModel(config)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 305, in __init__
    self.post_init()
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\modeling_utils.py", line 1159, in post_init
    self._backward_compatibility_gradient_checkpointing()
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\modeling_utils.py", line 1163, in _backward_compatibility_gradient_checkpointing
    self.gradient_checkpointing_enable()
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\modeling_utils.py", line 1872, in gradient_checkpointing_enable
    self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=gradient_checkpointing_func)
TypeError: _set_gradient_checkpointing() got an unexpected keyword argument 'enable'
init model ...
2023-11-03 18:34:46.606 Uncaught app exception
Traceback (most recent call last):
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "E:\wrl\PythonCode\Baichuan2\cli_demo.py", line 91, in <module>
    main()
  File "E:\wrl\PythonCode\Baichuan2\cli_demo.py", line 52, in main
    model, tokenizer = init_model()
  File "E:\wrl\PythonCode\Baichuan2\cli_demo.py", line 13, in init_model
    model = AutoModelForCausalLM.from_pretrained(
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 670, in from_pretrained
    return super(BaichuanForCausalLM, cls).from_pretrained(pretrained_model_name_or_path, *model_args,
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\modeling_utils.py", line 3236, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 539, in __init__
    self.model = BaichuanModel(config)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat\modeling_baichuan.py", line 305, in __init__
    self.post_init()
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\modeling_utils.py", line 1159, in post_init
    self._backward_compatibility_gradient_checkpointing()
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\modeling_utils.py", line 1163, in _backward_compatibility_gradient_checkpointing
    self.gradient_checkpointing_enable()
  File "E:\wrl\PythonCode\Baichuan2\venv\lib\site-packages\transformers\modeling_utils.py", line 1872, in gradient_checkpointing_enable
    self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=gradient_checkpointing_func)
TypeError: _set_gradient_checkpointing() got an unexpected keyword argument 'enable'

**Comment by wrl1224** [comment]
遇到这个问题不知道怎么解决，需要帮助。

**Comment by newfyu** [comment]
同样问题

**Comment by SevenMpp** [comment]
请问您这个问题解决了吗？？

**Comment by newfyu** [comment]
就按我说的版本降级就可以了

**Comment by Zhu-DaBao** [comment]
> 同样问题, 降级transformers==4.33.1 and tokenizers==0.13.3
问题：TypeError: _set_gradient_checkpointing() got an unexpected keyword argument 'enable'
感谢大佬，实测有用，这个问题困扰了我好几天
运行下面代码就可以降级了
pip install transformers==4.33.1
pip install tokenizers==0.13.3
