### ISSUE TITLE
离线int8量化报错

### ISSUE THREAD

**Issue by guiniao** [baichuan-inc/Baichuan2#262]
使用如下代码离线量化模型：
model = AutoModelForCausalLM.from_pretrained("./models", load_in_8bit=True, device_map="auto", trust_remote_code=True)
model.save_pretrained("./models_int8")

torch版本为2.1.0

报如下错误，是因为包版本不对吗
Traceback (most recent call last):
  File "/home/lproot/dl/huggingface/Baichuan2-main/model_int8.py", line 5, in <module>
    model = AutoModelForCausalLM.from_pretrained("./models", load_in_8bit=True, device_map="auto", trust_remote_code=True)
  File "/home/lproot/.conda/envs/llm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/home/lproot/.cache/huggingface/modules/transformers_modules/models/modeling_baichuan.py", line 670, in from_pretrained
    return super(BaichuanForCausalLM, cls).from_pretrained(pretrained_model_name_or_path, *model_args, 
  File "/home/lproot/.conda/envs/llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3236, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/lproot/.cache/huggingface/modules/transformers_modules/models/modeling_baichuan.py", line 539, in __init__
    self.model = BaichuanModel(config)
  File "/home/lproot/.cache/huggingface/modules/transformers_modules/models/modeling_baichuan.py", line 305, in __init__
    self.post_init()
  File "/home/lproot/.conda/envs/llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1159, in post_init
    self._backward_compatibility_gradient_checkpointing()
  File "/home/lproot/.conda/envs/llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1163, in _backward_compatibility_gradient_checkpointing
    self.gradient_checkpointing_enable()
  File "/home/lproot/.conda/envs/llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1872, in gradient_checkpointing_enable
    self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=gradient_checkpointing_func)
TypeError: _set_gradient_checkpointing() got an unexpected keyword argument 'enable'

**Comment by rrxsir** [comment]
一样的报错
