### ISSUE TITLE
AttributeError: 'list' object has no attribute 'as_dict'

### ISSUE THREAD

**Issue by hongxiuzhe** [baichuan-inc/Baichuan2#275]
部署baichuan-inc/Baichuan2-7B-Chat-4bits时报错

 File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 243, in _save_to_state_dict
    for k, v in self.weight.quant_state.as_dict(packed=True).items():
AttributeError: 'list' object has no attribute 'as_dict'

看了下源码有这个方法啊

**Comment by JiaXinSugar-114514** [comment]
我在加载Baichuan2-13B-Chat-4bits模型时遇到了同样的问题
init model ...
Traceback (most recent call last):
  File "/root/Baichuan2/cli_demo.py", line 88, in <module>
    main()
  File "/root/Baichuan2/cli_demo.py", line 49, in main
    model, tokenizer = init_model()
                       ^^^^^^^^^^^^
  File "/root/Baichuan2/cli_demo.py", line 14, in init_model
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 462, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat-4bits/modeling_baichuan.py", line 664, in from_pretrained
    dispatch_model(model, device_map=device_map)
  File "/root/anaconda3/lib/python3.11/site-packages/accelerate/big_modeling.py", line 343, in dispatch_model
    check_device_map(model, device_map)
  File "/root/anaconda3/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 1129, in check_device_map
    all_model_tensors = [name for name, _ in model.state_dict().items()]
                                             ^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1897, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/root/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1897, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/root/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1897, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  [Previous line repeated 2 more times]
  File "/root/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1894, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/root/anaconda3/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 237, in _save_to_state_dict
    for k, v in self.weight.quant_state.as_dict(packed=True).items():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'as_dict'

**Comment by JiaXinSugar-114514** [comment]
> 部署baichuan-inc/Baichuan2-7B-Chat-4bits时报错
> 
> File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 243, in _save_to_state_dict for k, v in self.weight.quant_state.as_dict(packed=True).items(): AttributeError: 'list' object has no attribute 'as_dict'
> 
> 看了下源码有这个方法啊。打印了下方法，也没打出来。 不知道是不是bitsandbytes没装好
> 
> <img alt="image" width="263" src="https://user-images.githubusercontent.com/18680152/283168980-32f4bc0b-ff1a-4406-acb3-9be9ef4ffcd9.png">

大佬，你最后咋解决的

**Comment by tjq9526** [comment]
降低bitsandbytes版本   pip install bitsandbytes==0.41.0

**Comment by wencan** [comment]
官方不能给个依赖库的版本列表吗？

**Comment by mihongyu** [comment]
降低bitsandbytes版本 pip install bitsandbytes==0.41.0  这个办法试了，能进入，但是输入文字就会报一个线程错误


欢迎使用百川大模型，输入进行对话，vim 多行输入，clear 清空历史，CTRL+C 中断生成，stream 开关流式生成，exit 结束。

用户：q

Baichuan 2：Exception in thread Thread-1 (generate):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\generation\utils.py", line 2047, in generate
    result = self._sample(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\generation\utils.py", line 3007, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\models\modeling_baichuan.py", line 685, in forward
    outputs = self.model(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\models\modeling_baichuan.py", line 461, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\models\modeling_baichuan.py", line 273, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\Administrator\.cache\huggingface\modules\transformers_modules\models\modeling_baichuan.py", line 205, in forward
    proj = self.W_pack(hidden_states)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\nn\modules.py", line 248, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\autograd\_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\autograd\_functions.py", line 516, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, state).to(A.dtype).t(), bias)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\functional.py", line 903, in dequantize_4bit
    absmax = dequantize_blockwise(absmax, state2)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\functional.py", line 713, in dequantize_blockwise
    lib.cdequantize_blockwise_cpu_fp32(get_ptr(quant_state[1]), get_ptr(A), get_ptr(quant_state[0]), get_ptr(out), ct.c_longlong(blocksize), ct.c_longlong(A.numel()))
AttributeError: 'NoneType' object has no attribute 'cdequantize_blockwise_cpu_fp32'
