### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by Guodongchang** [baichuan-inc/Baichuan2#283]
启动后，问一个问题报错
错误信息如下
```
用户：你好
Baichuan 2：Exception in thread Thread-2 (generate):
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\site-packages\transformers\generation\utils.py", line 1648, in generate
    return self.sample(
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\site-packages\transformers\generation\utils.py", line 2730, in sample    outputs = self(
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-chat\modeling_baichuan.py", line 693, in forward
    outputs = self.model(
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-chat\modeling_baichuan.py", line 467, in forward
    layer_outputs = decoder_layer(
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-chat\modeling_baichuan.py", line 244, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-chat\modeling_baichuan.py", line 147, in forward
    proj = self.W_pack(hidden_states)
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\baichuan\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
```

**Comment by QwYko-AHU** [comment]
请问解决了吗，我也遇到了同样的问题

**Comment by weipingtao** [comment]
你这是使用了CPU，可以将模型放到CUDA或者npu上。
例如:
model = model.cuda()
model = model.npu()
