### ISSUE TITLE
 Needs import model weight init func to run quantize.

### ISSUE THREAD

**Issue by seacdr** [baichuan-inc/Baichuan2#284]
win11 系统环境如下：
transformers==4.34.1
torch==2.1.0+cu121
torchaudio==2.1.0+cu121
torchvision==0.16.0+cu121
bitsandbytes==0.41.1
bitsandbytes-windows==0.37.5
scipy==1.11.4

报错：请问怎么处理，感谢！
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: DLL load failed while importing libtriton: 找不到指定的模块。
bin C:\Program Files\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
Traceback (most recent call last):
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat-4bits\modeling_baichuan.py", line 606, in from_pretrained
    from .quantizer import init_model_weight_int4
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat-4bits\quantizer.py", line 1, in <module>
    import bitsandbytes as bnb
  File "C:\Program Files\Python310\lib\site-packages\bitsandbytes\__init__.py", line 16, in <module>
    from .nn import modules
  File "C:\Program Files\Python310\lib\site-packages\bitsandbytes\nn\__init__.py", line 6, in <module>
    from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLinearVectorwise, StandardLinear
  File "C:\Program Files\Python310\lib\site-packages\bitsandbytes\nn\triton_based_modules.py", line 8, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "C:\Program Files\Python310\lib\site-packages\bitsandbytes\triton\dequantize_rowwise.py", line 10, in <module>
    import triton
  File "C:\Program Files\Python310\lib\site-packages\triton\__init__.py", line 10, in <module>
    from .runtime import Config, autotune, heuristics, JITFunction, KernelInterface
  File "C:\Program Files\Python310\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import Config, Heuristics, autotune, heuristics  # noqa: F401
  File "C:\Program Files\Python310\lib\site-packages\triton\runtime\autotuner.py", line 7, in <module>
    from ..testing import do_bench
  File "C:\Program Files\Python310\lib\site-packages\triton\testing.py", line 9, in <module>
    import triton._C.libtriton.triton as _triton
ImportError: DLL load failed while importing libtriton: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\demo.py", line 5, in <module>
    model = AutoModelForCausalLM.from_pretrained("models/Baichuan2-13B-Chat-4bits", device_map="auto", torch_dtype=torch.bfloat16, trust_remote_code=True)
  File "C:\Program Files\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 560, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat-4bits\modeling_baichuan.py", line 611, in from_pretrained
    raise ImportError(f"Needs import model weight init func to run quantize.")
ImportError: Needs import model weight init func to run quantize.

**Comment by seacdr** [comment]
另外Baichuan2-7B-Chat-4bits报错：
Traceback (most recent call last):
  File "D:\AI\demo.py", line 4, in <module>
    tokenizer = AutoTokenizer.from_pretrained("models/Baichuan2-7B-Chat-4bits", use_fast=False, trust_remote_code=True)
  File "C:\Program Files\Python310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 2045, in from_pretrained
    return cls._from_pretrained(
  File "C:\Program Files\Python310\lib\site-packages\transformers\tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Baichuan2-7B-Chat-4bits\tokenization_baichuan.py", line 80, in __init__
    self.sp_model.Load(vocab_file)
  File "C:\Program Files\Python310\lib\site-packages\sentencepiece\__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "C:\Program Files\Python310\lib\site-packages\sentencepiece\__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

**Comment by seacdr** [comment]
重新安装Python环境+依赖，成功运行。

**Comment by joy1101** [comment]
> 重新安装Python环境+依赖，成功运行。

我也遇到这样的问题了，win11 系统。 你重装时triton-2.0.0-cp310-cp310-win_amd64.whl这个哪里下载的？ 还有python安装目录换了么？我也是这目录

**Comment by joy1101** [comment]
> torch==2.1.0+cu121

重装时，这个版本变了么？
