### ISSUE TITLE
报错 AttributeError: 'str' object has no attribute 'to'

### ISSUE THREAD

**Issue by heiheiheibj** [baichuan-inc/Baichuan2#29]
CUDA SETUP: Loading binary /root/anaconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
Traceback (most recent call last):
  File "/usr/local/Baichuan2/cli_demo.py", line 88, in <module>
    main()
  File "/usr/local/Baichuan2/cli_demo.py", line 49, in main
    model, tokenizer = init_model()
  File "/usr/local/Baichuan2/cli_demo.py", line 14, in init_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 488, in from_pretrained
    return model_class.from_pretrained(
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat-4bits/modeling_baichuan.py", line 664, in from_pretrained
    dispatch_model(model, device_map=device_map)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/big_modeling.py", line 371, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/hooks.py", line 507, in attach_align_device_hook_on_blocks
    attach_execution_device_hook(module, execution_device[module_name])
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/hooks.py", line 347, in attach_execution_device_hook
    attach_execution_device_hook(child, execution_device)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/hooks.py", line 347, in attach_execution_device_hook
    attach_execution_device_hook(child, execution_device)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/hooks.py", line 347, in attach_execution_device_hook
    attach_execution_device_hook(child, execution_device)
  [Previous line repeated 2 more times]
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/hooks.py", line 340, in attach_execution_device_hook
    add_hook_to_module(module, AlignDevicesHook(execution_device, skip_keys=skip_keys))
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/hooks.py", line 253, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 292, in set_module_tensor_to_device
    new_value = old_value.to(device)
  File "/root/anaconda3/envs/llama2/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 191, in to
    s[-2][0] = s[-2][0].to(device) # offset
AttributeError: 'str' object has no attribute 'to'

谢谢

**Comment by jameswu2014** [comment]
能不能把代码贴出来看一下？

**Comment by heiheiheibj** [comment]
> bitsandbytes 升级到最新版本，就可以了 pip install bitsandbytes==0.41.1

可以了，非常感谢
