### ISSUE TITLE
运行web_demo.py报错

### ISSUE THREAD

**Issue by fxb392** [baichuan-inc/Baichuan2#342]
2024-01-07 16:56:48.658 Session state does not function when running a script without `streamlit run`
Traceback (most recent call last):
  File "/home/wuke/miniconda3/envs/fxb/lib/python3.9/site-packages/streamlit/runtime/state/session_state.py", line 394, in __getitem__
    return self._getitem(widget_id, key)
  File "/home/wuke/miniconda3/envs/fxb/lib/python3.9/site-packages/streamlit/runtime/state/session_state.py", line 439, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wuke/miniconda3/envs/fxb/lib/python3.9/site-packages/streamlit/runtime/state/session_state_proxy.py", line 119, in __getattr__
    return self[key]
  File "/home/wuke/miniconda3/envs/fxb/lib/python3.9/site-packages/streamlit/runtime/state/session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
  File "/home/wuke/miniconda3/envs/fxb/lib/python3.9/site-packages/streamlit/runtime/state/safe_session_state.py", line 89, in __getitem__
    return self._state[key]
  File "/home/wuke/miniconda3/envs/fxb/lib/python3.9/site-packages/streamlit/runtime/state/session_state.py", line 396, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "messages". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wuke/project/fxb/Baichuan2-main/web_demo.py", line 72, in <module>
    main()
  File "/home/wuke/project/fxb/Baichuan2-main/web_demo.py", line 52, in main
    messages = init_chat_history()
  File "/home/wuke/project/fxb/Baichuan2-main/web_demo.py", line 47, in init_chat_history
    return st.session_state.messages
  File "/home/wuke/miniconda3/envs/fxb/lib/python3.9/site-packages/streamlit/runtime/state/session_state_proxy.py", line 121, in __getattr__
    raise AttributeError(_missing_attr_error_message(key))
AttributeError: st.session_state has no attribute "messages". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization

**Comment by qianma819** [comment]
这个为什么关掉了？遇到同样的问题

**Comment by sankexin** [comment]
streamlit run web_demo.py

Local URL: http://localhost:8501
