### ISSUE TITLE
运行需要什么样的python环境？提示xFormers版本问题

### ISSUE THREAD

**Issue by qianma819** [baichuan-inc/Baichuan2#359]
streamlit run web_demo.py失败，提示xFormers版本问题

**Comment by qianma819** [comment]
log如下：
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
Traceback (most recent call last):
  File "/home/brother/baichuannewnev/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/home/brother/baichuannewnev/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 498, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError
目前pytorch不支持_set_gradient_checkpointing，这个要咋整？之前跑起来的同学是用的啥版本？
