### ISSUE TITLE
Baichuan2-13B-Chat-4bits 微调报错

### ISSUE THREAD

**Issue by pjw-cmd** [baichuan-inc/Baichuan2#421]
我在linux环境下跑Baichuan2-13B-Chat-4bits这个模型报错：
这是报错信息：[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/peft/peft_model.py", line 737, in __getattr__
[rank0]:     return super().__getattr__(name)  # defer to nn.Module's logic
[rank0]:   File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
[rank0]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank0]: AttributeError: 'PeftModelForCausalLM' object has no attribute 'hf_quantizer'

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 356, in __getattr__
[rank0]:     return super().__getattr__(name)  # defer to nn.Module's logic
[rank0]:   File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
[rank0]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank0]: AttributeError: 'LoraModel' object has no attribute 'hf_quantizer'

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data2/pengjw/Baichuan2/fine-tune/fine-tune.py", line 153, in <module>
[rank0]:     train()
[rank0]:   File "/data2/pengjw/Baichuan2/fine-tune/fine-tune.py", line 144, in train
[rank0]:     trainer = transformers.Trainer(
[rank0]:   File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/transformers/trainer.py", line 489, in __init__
[rank0]:     f"The model you are trying to fine-tune is quantized with {model.hf_quantizer.quantization_config.quant_method}"
[rank0]:   File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/peft/peft_model.py", line 741, in __getattr__
[rank0]:     return getattr(self.base_model, name)
[rank0]:   File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 360, in __getattr__
[rank0]:     return getattr(self.model, name)
[rank0]:   File "/data/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
[rank0]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank0]: AttributeError: 'BaichuanForCausalLM' object has no attribute 'hf_quantizer'. Did you mean: 'is_quantized'?
[2024-09-11 10:31:54,330] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 22049
[2024-09-11 10:31:54,330] [ERROR] [launch.py:325:sigkill_handler] ['/data/anaconda3/envs/py310/bin/python', '-u', 'fine-tune.py', '--local_rank=0', '--report_to', 'none', '--data_path', 'data/belle_chat_ramdon_10k.json', '--model_name_or_path', '/data2/pengjw/Baichuan2/model_pth/Baichuan2-13B-Chat-4bits', '--output_dir', 'output', '--model_max_length', '512', '--num_train_epochs', '4', '--per_device_train_batch_size', '16', '--gradient_accumulation_steps', '1', '--save_strategy', 'epoch', '--learning_rate', '2e-5', '--lr_scheduler_type', 'constant', '--adam_beta1', '0.9', '--adam_beta2', '0.98', '--adam_epsilon', '1e-8', '--max_grad_norm', '1.0', '--weight_decay', '1e-4', '--warmup_ratio', '0.0', '--logging_steps', '1', '--gradient_checkpointing', 'True', '--deepspeed', 'ds_config.json', '--bf16', 'True', '--tf32', 'True', '--use_lora', 'True'] exits with return code = 1
有大佬可以帮忙看下是什么原因吗？非常感谢。

**Comment by linxia1** [comment]
我微调4bit的模型也是报错，我看其他issue说4bit不能微调，但是可以微调7B-chat，我现在打算去看看能不能先微调7B-chat，然后再量化到4bit
