### ISSUE TITLE
量化版本报错 

### ISSUE THREAD

**Issue by bihui9968** [baichuan-inc/Baichuan2#53]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py", line 1648, in generate
    return self.sample(
  File "/opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py", line 2766, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by jameswu2014** [comment]
Please post your code

**Comment by bihui9968** [comment]
> 

我直接运行的起页面脚本，刚开始几次是好的，后来显卡内存溢出，我把容器重启了以后再起页面脚本，就报这个错了，页面回复的是乱码。

**Comment by jameswu2014** [comment]
看上去是要重启电脑？GPU出了问题
